path:  ${ROOT_DIRECTORY}/default-dataset
train: ${ROOT_DIRECTORY}/default-dataset/train
test: ${ROOT_DIRECTORY}/default-dataset/test
val: ${ROOT_DIRECTORY}/default-dataset/valid

#Classes
nc: 8

#classes names
names: [
  "barrier up",
  "barrier down",
  "car parked",
  "car out",
  "parking lot occupied",
  "car in",
  "special car",
  "parking lot free",
]
