path:  /Users/batiukmaks/PycharmProjects/Intelligent-Parking-Management-System/default-dataset
train: /Users/batiukmaks/PycharmProjects/Intelligent-Parking-Management-System/default-dataset/train
test: /Users/batiukmaks/PycharmProjects/Intelligent-Parking-Management-System/default-dataset/test
val: /Users/batiukmaks/PycharmProjects/Intelligent-Parking-Management-System/default-dataset/valid

#Classes
nc: 5 # replace according to your number of classes

#classes names
#replace all class names list with your classes names
names: ["barrier up", "car parked", "car in", "barrier down", "car out"]
