path:  /home/batiukmaks/Documents/Intelligent-Parking-Management-System/my-parking/dataset
train: /home/batiukmaks/Documents/Intelligent-Parking-Management-System/my-parking/dataset/train
test: /home/batiukmaks/Documents/Intelligent-Parking-Management-System/my-parking/dataset/test
val: /home/batiukmaks/Documents/Intelligent-Parking-Management-System/my-parking/dataset/valid

#Classes
nc: 5 # replace according to your number of classes

#classes names
#replace all class names list with your classes names
names: ["barrier up", "car parked", "car in", "barrier down", "car out"]
